### ISSUE TITLE
Wiki Page Home

### ISSUE THREAD

**Issue by paulobocanegra** [shiwen1209/SyncedUp#1]
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a description sentence of the app
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

**Comment by paulobocanegra** [comment]
Great progress!

**Comment by paulobocanegra** [comment]
Looks great! 💯

**Comment by paulobocanegra** [comment]
Let's update the link for the backend routes. Right now is linking to "Create new Page"

**Comment by shiwen1209** [comment]
updated the link for backend route

**Comment by paulobocanegra** [comment]
Great job!
