### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by paulobocanegra** [shiwen1209/SyncedUp#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/mvp-checklist) or they have clarified them with you
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

**Comment by paulobocanegra** [comment]
Let's move the description to the Home page.

**Comment by paulobocanegra** [comment]
Let's change the format and data. Right now is showing Chrips (blubird mvp list)

**Comment by paulobocanegra** [comment]
Nice update! 
Now we need to list each specification for the MVPs in bullet points to make it easy to read for recruiters/engineers.

**Comment by shiwen1209** [comment]
updated all mvps

**Comment by paulobocanegra** [comment]
Looks great!
