### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by paulobocanegra** [shiwen1209/SyncedUp#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [ ] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by paulobocanegra** [comment]
Let's add the bullet points to expand on foreign keys and back ticks on each column name.

**Comment by shiwen1209** [comment]
finished!

**Comment by paulobocanegra** [comment]
The last detail to change is back ticks on the column names under the tables like :

`user_id` references users
index on `user_id`

**Comment by shiwen1209** [comment]
done!
