### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [shiwen1209/SyncedUp#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
We need to format it.

**Comment by shiwen1209** [comment]
updated, linkedin app does not appear to have any url with wildcard...

**Comment by paulobocanegra** [comment]
Looks great!
